### ISSUE TITLE
sql FIle missing

### ISSUE THREAD

**Issue by RootViper4** [dulanjayabhanu/OSMS#1]
Hi, osms.sql file is missing

**Comment by dulanjayabhanu** [comment]
Hi @RootViper4 ,

Thank you for bringing this to my attention. I appreciate your vigilance and effort in helping improve the project.

The `osms.sql` file has now been added to the **main code base**. It is also attached to the `OSMS v1.0.0` release.

Thanks again for your support!

**Comment by RootViper4** [comment]
Thanks a lot 🙏
